Repository JA-yeong-eop-JA-moeu-JA/Jajaja_BE, pull requests merged in 2025-07, with the labels that each got.

#4 Feat/#2 response swagger
  .gitignore
  build.gradle
  src/main/java/com/jajaja/apiPayload/ApiResponse.java
  src/main/java/com/jajaja/apiPayload/code/BaseCode.java
  src/main/java/com/jajaja/apiPayload/code/BaseErrorCode.java
  src/main/java/com/jajaja/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/jajaja/apiPayload/code/ReasonDTO.java
  src/main/java/com/jajaja/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/jajaja/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/jajaja/apiPayload/config/SwaggerConfig.java
  src/main/java/com/jajaja/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/jajaja/apiPayload/exception/GeneralException.java
  src/main/java/com/jajaja/apiPayload/exception/handler/TempHandler.java
  src/main/resources/application.yml
Labels: ✨ Feature

#14 ⚙️ setting: QueryDSL 설정
  .gitignore
  build.gradle
  gradlew
  src/main/generated/com/jajaja/domain/cart/entity/QCart.java
  src/main/generated/com/jajaja/domain/cart/entity/QCartProduct.java
  src/main/generated/com/jajaja/domain/coupon/entity/QCoupon.java
  src/main/generated/com/jajaja/domain/delivery/entity/QDelivery.java
  src/main/generated/com/jajaja/domain/notification/entity/QNotification.java
  src/main/generated/com/jajaja/domain/order/entity/QOrder.java
  src/main/generated/com/jajaja/domain/order/entity/QOrderProduct.java
  src/main/generated/com/jajaja/domain/point/entity/QPoint.java
  src/main/generated/com/jajaja/domain/product/entity/QBusinessCategory.java
  src/main/generated/com/jajaja/domain/product/entity/QProduct.java
  src/main/generated/com/jajaja/domain/product/entity/QProductOption.java
  src/main/generated/com/jajaja/domain/product/entity/QProductSales.java
  src/main/generated/com/jajaja/domain/product/entity/category/QCategory.java
  src/main/generated/com/jajaja/domain/product/entity/category/QCategoryGroup.java
  src/main/generated/com/jajaja/domain/product/entity/category/QProductSubCategory.java
  src/main/generated/com/jajaja/domain/product/entity/category/QSubCategory.java
  src/main/generated/com/jajaja/domain/review/entity/QReview.java
  src/main/generated/com/jajaja/domain/review/entity/QReviewImage.java
  src/main/generated/com/jajaja/domain/review/entity/QReviewLike.java
  src/main/generated/com/jajaja/domain/search/entity/QSearch.java
  src/main/generated/com/jajaja/domain/team/entity/QTeam.java
  src/main/generated/com/jajaja/domain/team/entity/QTeamMember.java
  src/main/generated/com/jajaja/domain/user/entity/QUser.java
  src/main/generated/com/jajaja/domain/user/entity/QUserBusinessCategory.java
  src/main/generated/com/jajaja/domain/user/entity/QUserCoupon.java
  src/main/generated/com/jajaja/global/common/domain/QBaseEntity.java
  src/main/java/com/jajaja/global/config/QueryDSLConfig.java
Labels: ⚙️ Setting

#11 ✨ feat: 상품 관련 API 구현
  src/main/generated/com/jajaja/domain/product/entity/QProduct.java
  src/main/java/com/jajaja/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/jajaja/domain/product/controller/ProductController.java
  src/main/java/com/jajaja/domain/product/dto/response/ProductDetailResponseDto.java
  src/main/java/com/jajaja/domain/product/dto/response/ProductOptionResponseDto.java
  src/main/java/com/jajaja/domain/product/entity/Product.java
  src/main/java/com/jajaja/domain/product/repository/ProductRepository.java
  src/main/java/com/jajaja/domain/product/service/ProductOptionQueryService.java
  src/main/java/com/jajaja/domain/product/service/ProductOptionQueryServiceImpl.java
  src/main/java/com/jajaja/domain/product/service/ProductQueryService.java
  src/main/java/com/jajaja/domain/product/service/ProductQueryServiceImpl.java
  src/main/java/com/jajaja/domain/product/util/ProductPriceCalculator.java
  src/main/java/com/jajaja/domain/review/converter/ReviewConverter.java
  src/main/java/com/jajaja/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/jajaja/domain/review/repository/ReviewRepository.java
  src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/jajaja/domain/team/converter/TeamConverter.java
  src/main/java/com/jajaja/domain/team/dto/response/TeamResponseDto.java
  src/main/java/com/jajaja/domain/team/repository/TeamRepository.java
  src/main/java/com/jajaja/domain/team/repository/TeamRepositoryCustom.java
  src/main/java/com/jajaja/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/jajaja/domain/user/converter/UserConverter.java
  src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/jajaja/global/apiPayload/exception/custom/BadRequestException.java
  src/main/java/com/jajaja/global/config/security/annotation/Auth.java
Labels: ✨ Feature

#12 ✨ feat: 온보딩 업종 선택 API 구현
  src/main/java/com/jajaja/domain/product/entity/repository/BusinessCategoryRepository.java
  src/main/java/com/jajaja/domain/user/controller/UserBusinessCategoryController.java
  src/main/java/com/jajaja/domain/user/dto/UserBusinessCategoryRequestDto.java
  src/main/java/com/jajaja/domain/user/entity/UserBusinessCategory.java
  src/main/java/com/jajaja/domain/user/repository/UserBusinessCategoryRepository.java
  src/main/java/com/jajaja/domain/user/service/UserBusinessCategoryCommandService.java
  src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#19 ✨ feat: 장바구니 관련 API 구현
  src/main/java/com/jajaja/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/jajaja/domain/cart/controller/CartController.java
  src/main/java/com/jajaja/domain/cart/converter/CartConverter.java
  src/main/java/com/jajaja/domain/cart/dto/CartProductAddRequestDto.java
  src/main/java/com/jajaja/domain/cart/dto/CartProductResponseDto.java
  src/main/java/com/jajaja/domain/cart/dto/CartResponseDto.java
  src/main/java/com/jajaja/domain/cart/entity/Cart.java
  src/main/java/com/jajaja/domain/cart/entity/CartProduct.java
  src/main/java/com/jajaja/domain/cart/repository/CartProductRepository.java
  src/main/java/com/jajaja/domain/cart/repository/CartRepository.java
  src/main/java/com/jajaja/domain/cart/repository/CartRepositoryCustom.java
  src/main/java/com/jajaja/domain/cart/repository/CartRepositoryImpl.java
  src/main/java/com/jajaja/domain/cart/service/CartCommandService.java
  src/main/java/com/jajaja/domain/cart/service/CartCommandServiceImpl.java
  src/main/java/com/jajaja/domain/cart/service/CartComponent.java
  src/main/java/com/jajaja/domain/cart/service/CartQueryService.java
  src/main/java/com/jajaja/domain/cart/service/CartQueryServiceImpl.java
  src/main/java/com/jajaja/domain/coupon/dto/AppliedCouponResponseDto.java
  src/main/java/com/jajaja/domain/coupon/dto/CouponConditionDto.java
  src/main/java/com/jajaja/domain/product/repository/ProductOptionRepository.java
  src/main/java/com/jajaja/domain/team/repository/TeamCommandRepository.java
  src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/jajaja/global/apiPayload/exception/handler/CartHandler.java
Labels: ✨ Feature

#22 🐛 fix: 쿠폰 관련 null 처리
  src/main/java/com/jajaja/domain/cart/converter/CartConverter.java
  src/main/java/com/jajaja/domain/cart/service/CartCommandServiceImpl.java
  src/main/java/com/jajaja/domain/cart/service/CartCommonService.java
  src/main/java/com/jajaja/domain/cart/service/CartQueryServiceImpl.java
  src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
Labels: 🐞 BugFix, :hammer: Refactor

#24 ✨ feat: 팀 관련 API 구현
  src/main/java/com/jajaja/Application.java
  src/main/java/com/jajaja/domain/cart/controller/CartController.java
  src/main/java/com/jajaja/domain/cart/entity/Cart.java
  src/main/java/com/jajaja/domain/team/controller/TeamController.java
  src/main/java/com/jajaja/domain/team/dto/response/TeamCreateResponseDto.java
  src/main/java/com/jajaja/domain/team/entity/Team.java
  src/main/java/com/jajaja/domain/team/repository/TeamRepositoryCustom.java
  src/main/java/com/jajaja/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/jajaja/domain/team/service/TeamCommandService.java
  src/main/java/com/jajaja/domain/team/service/TeamCommandServiceImpl.java
  src/main/java/com/jajaja/domain/team/service/TeamCommonService.java
  src/main/java/com/jajaja/domain/user/entity/User.java
  src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/jajaja/global/scheduler/TeamExpireScheduler.java
Labels: ✨ Feature

#30 ✨ feat: 주문 조회 관련 API 구현
  src/main/java/com/jajaja/domain/order/controller/OrderController.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderDeliveryDto.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderDetailResponseDto.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderItemDto.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderItemProductDto.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderListDto.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderPaymentDto.java
  src/main/java/com/jajaja/domain/order/dto/response/PagingOrderListResponseDto.java
  src/main/java/com/jajaja/domain/order/entity/Order.java
  src/main/java/com/jajaja/domain/order/entity/OrderProduct.java
  src/main/java/com/jajaja/domain/order/repository/OrderRepository.java
  src/main/java/com/jajaja/domain/order/repository/OrderRepositoryCustom.java
  src/main/java/com/jajaja/domain/order/repository/OrderRepositoryImpl.java
  src/main/java/com/jajaja/domain/order/service/OrderQueryService.java
  src/main/java/com/jajaja/domain/order/service/OrderQueryServiceImpl.java
  src/main/java/com/jajaja/domain/team/entity/Team.java
  src/main/java/com/jajaja/global/apiPayload/PageResponse.java
  src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#28 ✨ feat: 카테고리 관련 조회 API 구현
  src/main/java/com/jajaja/domain/product/controller/CategoryController.java
  src/main/java/com/jajaja/domain/product/controller/ProductController.java
  src/main/java/com/jajaja/domain/product/dto/response/CategoryProductListResponseDto.java
  src/main/java/com/jajaja/domain/product/dto/response/CategoryResponseDto.java
  src/main/java/com/jajaja/domain/product/dto/response/SubCategoryResponseDto.java
  src/main/java/com/jajaja/domain/product/entity/enums/ProductSortType.java
  src/main/java/com/jajaja/domain/product/repository/CategoryRepositoryCustom.java
  src/main/java/com/jajaja/domain/product/repository/CategoryRepositoryImpl.java
  src/main/java/com/jajaja/domain/product/repository/ProductRepository.java
  src/main/java/com/jajaja/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/jajaja/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/jajaja/domain/product/repository/ProductSalesRepositoryCustom.java
  src/main/java/com/jajaja/domain/product/repository/ProductSalesRepositoryImpl.java
  src/main/java/com/jajaja/domain/product/service/CategoryQueryService.java
  src/main/java/com/jajaja/domain/product/service/CategoryQueryServiceImpl.java
  src/main/java/com/jajaja/domain/product/service/ProductQueryService.java
  src/main/java/com/jajaja/domain/product/service/ProductQueryServiceImpl.java
  src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/jajaja/global/config/security/SecurityConfig.java
Labels: ✨ Feature

#29 ✨ feat: 홈 검색 관련 API 구현
  src/main/java/com/jajaja/domain/product/repository/ProductSalesRepositoryCustom.java
  src/main/java/com/jajaja/domain/product/repository/ProductSalesRepositoryImpl.java
  src/main/java/com/jajaja/domain/search/controller/SearchController.java
  src/main/java/com/jajaja/domain/search/dto/PopularSearchKeywordsResponseDto.java
  src/main/java/com/jajaja/domain/search/entity/Search.java
  src/main/java/com/jajaja/domain/search/entity/enums/SearchSort.java
  src/main/java/com/jajaja/domain/search/repository/SearchRepository.java
  src/main/java/com/jajaja/domain/search/repository/SearchRepositoryCustom.java
  src/main/java/com/jajaja/domain/search/repository/SearchRepositoryCustomImpl.java
  src/main/java/com/jajaja/domain/search/service/SearchService.java
  src/main/java/com/jajaja/domain/search/service/SearchServiceImpl.java
  src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/jajaja/global/config/security/SecurityConfig.java
Labels: ✨ Feature

#35 ♻️ refactor: User 엔티티를 Member로 이름 변경
  src/main/java/com/jajaja/domain/auth/dto/CustomOAuth2User.java
  src/main/java/com/jajaja/domain/auth/dto/GoogleResponseDto.java
  src/main/java/com/jajaja/domain/auth/dto/KakaoResponseDto.java
  src/main/java/com/jajaja/domain/auth/dto/OAuth2ResponseDto.java
  src/main/java/com/jajaja/domain/auth/dto/UserDto.java
  src/main/java/com/jajaja/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/jajaja/domain/cart/entity/Cart.java
  src/main/java/com/jajaja/domain/coupon/entity/Coupon.java
  src/main/java/com/jajaja/domain/delivery/entity/Delivery.java
  src/main/java/com/jajaja/domain/member/controller/MemberBusinessCategoryController.java
  src/main/java/com/jajaja/domain/member/converter/MemberConverter.java
  src/main/java/com/jajaja/domain/member/dto/MemberBusinessCategoryRequestDto.java
  src/main/java/com/jajaja/domain/member/entity/Member.java
  src/main/java/com/jajaja/domain/member/entity/MemberBusinessCategory.java
  src/main/java/com/jajaja/domain/member/entity/MemberCoupon.java
  src/main/java/com/jajaja/domain/member/entity/enums/OauthType.java
  src/main/java/com/jajaja/domain/member/repository/MemberBusinessCategoryRepository.java
  src/main/java/com/jajaja/domain/member/repository/MemberRepository.java
  src/main/java/com/jajaja/domain/member/service/MemberBusinessCategoryCommandService.java
  src/main/java/com/jajaja/domain/member/service/MemberBusinessCategoryCommandServiceImpl.java
  src/main/java/com/jajaja/domain/notification/entity/Notification.java
  src/main/java/com/jajaja/domain/order/entity/Order.java
  src/main/java/com/jajaja/domain/point/entity/Point.java
  src/main/java/com/jajaja/domain/product/entity/BusinessCategory.java
  src/main/java/com/jajaja/domain/product/service/ProductQueryServiceImpl.java
  src/main/java/com/jajaja/domain/review/entity/Review.java
  src/main/java/com/jajaja/domain/review/entity/ReviewLike.java
  src/main/java/com/jajaja/domain/team/entity/Team.java
  src/main/java/com/jajaja/domain/team/entity/TeamMember.java
  src/main/java/com/jajaja/domain/team/service/TeamCommandServiceImpl.java
  src/main/java/com/jajaja/domain/team/service/TeamCommonService.java
  src/main/java/com/jajaja/domain/user/entity/enums/OauthType.java
  src/main/java/com/jajaja/domain/user/repository/UserBusinessCategoryRepository.java
  src/main/java/com/jajaja/domain/user/repository/UserRepository.java
  src/main/java/com/jajaja/domain/user/service/UserBusinessCategoryCommandService.java
Labels: :hammer: Refactor

#33 ✨ feat: 리뷰 상세 조회 관련 API 구현
  src/main/java/com/jajaja/domain/product/dto/response/ProductDetailResponseDto.java
  src/main/java/com/jajaja/domain/product/service/ProductCommonService.java
  src/main/java/com/jajaja/domain/product/service/ProductCommonServiceImpl.java
  src/main/java/com/jajaja/domain/product/service/ProductOptionQueryServiceImpl.java
  src/main/java/com/jajaja/domain/product/service/ProductQueryServiceImpl.java
  src/main/java/com/jajaja/domain/product/util/ProductPriceCalculator.java
  src/main/java/com/jajaja/domain/review/controller/ReviewController.java
  src/main/java/com/jajaja/domain/review/converter/ReviewConverter.java
  src/main/java/com/jajaja/domain/review/dto/response/PagingReviewListResponseDto.java
  src/main/java/com/jajaja/domain/review/dto/response/ReviewBriefResponseDto.java
  src/main/java/com/jajaja/domain/review/dto/response/ReviewItemDto.java
  src/main/java/com/jajaja/domain/review/dto/response/ReviewListDto.java
  src/main/java/com/jajaja/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/jajaja/domain/review/repository/ReviewImageRepository.java
  src/main/java/com/jajaja/domain/review/repository/ReviewImageRepositoryCustom.java
  src/main/java/com/jajaja/domain/review/repository/ReviewImageRepositoryImpl.java
  src/main/java/com/jajaja/domain/review/repository/ReviewLikeRepository.java
  src/main/java/com/jajaja/domain/review/repository/ReviewLikeRepositoryCustom.java
  src/main/java/com/jajaja/domain/review/repository/ReviewLikeRepositoryImpl.java
  src/main/java/com/jajaja/domain/review/repository/ReviewRepository.java
  src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/jajaja/domain/review/service/ReviewQueryService.java
  src/main/java/com/jajaja/domain/review/service/ReviewQueryServiceImpl.java
  src/main/java/com/jajaja/domain/team/dto/response/TeamListDto.java
  src/main/java/com/jajaja/global/config/security/SecurityConfig.java
Labels: ✨ Feature

#43 ✨ feat: 사진 리뷰 상세 조회 API 구현
  src/main/java/com/jajaja/domain/review/controller/ReviewController.java
  src/main/java/com/jajaja/domain/review/dto/response/PagingReviewImageListResponseDto.java
  src/main/java/com/jajaja/domain/review/dto/response/ReviewImageListDto.java
  src/main/java/com/jajaja/domain/review/repository/ReviewImageRepositoryCustom.java
  src/main/java/com/jajaja/domain/review/repository/ReviewImageRepositoryImpl.java
  src/main/java/com/jajaja/domain/review/service/ReviewQueryService.java
  src/main/java/com/jajaja/domain/review/service/ReviewQueryServiceImpl.java
Labels: ✨ Feature

#44 ✨ feat: 리뷰 좋아요/취소 API 구현
  src/main/java/com/jajaja/domain/member/service/MemberBusinessCategoryCommandServiceImpl.java
  src/main/java/com/jajaja/domain/product/controller/ProductController.java
  src/main/java/com/jajaja/domain/product/service/ProductQueryService.java
  src/main/java/com/jajaja/domain/product/service/ProductQueryServiceImpl.java
  src/main/java/com/jajaja/domain/review/controller/ReviewController.java
  src/main/java/com/jajaja/domain/review/dto/response/ReviewLikeResponseDto.java
  src/main/java/com/jajaja/domain/review/repository/ReviewLikeRepository.java
  src/main/java/com/jajaja/domain/review/repository/ReviewLikeRepositoryCustom.java
  src/main/java/com/jajaja/domain/review/repository/ReviewLikeRepositoryImpl.java
  src/main/java/com/jajaja/domain/review/service/ReviewLikeCommandService.java
  src/main/java/com/jajaja/domain/review/service/ReviewLikeCommandServiceImpl.java
  src/main/java/com/jajaja/domain/review/service/ReviewQueryService.java
  src/main/java/com/jajaja/domain/review/service/ReviewQueryServiceImpl.java
  src/main/java/com/jajaja/domain/team/controller/TeamController.java
  src/main/java/com/jajaja/domain/team/service/TeamCommandService.java
  src/main/java/com/jajaja/domain/team/service/TeamCommandServiceImpl.java
  src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/jajaja/global/config/security/SecurityConfig.java
Labels: ✨ Feature

#53 ✨ feat: S3 presigned url 구현
  build.gradle
  src/main/java/com/jajaja/global/S3/S3Config.java
  src/main/java/com/jajaja/global/S3/controller/S3Controller.java
  src/main/java/com/jajaja/global/S3/dto/request/PresignedUploadRequestDtp.java
  src/main/java/com/jajaja/global/S3/dto/response/PresignedUrlUploadResponseDto.java
  src/main/java/com/jajaja/global/S3/service/S3Service.java
  src/main/resources/application.yml
Labels: ✨ Feature

#51 ✨ feat: 배송지 관련 API 구현
  src/main/java/com/jajaja/domain/delivery/controller/DeliveryController.java
  src/main/java/com/jajaja/domain/delivery/dto/DeliveryRequestDto.java
  src/main/java/com/jajaja/domain/delivery/dto/DeliveryResponseDto.java
  src/main/java/com/jajaja/domain/delivery/entity/Delivery.java
  src/main/java/com/jajaja/domain/delivery/repository/DeliveryRepository.java
  src/main/java/com/jajaja/domain/delivery/service/DeliveryCommandService.java
  src/main/java/com/jajaja/domain/delivery/service/DeliveryCommandServiceImpl.java
  src/main/java/com/jajaja/domain/delivery/service/DeliveryQueryService.java
  src/main/java/com/jajaja/domain/delivery/service/DeliveryQueryServiceImpl.java
  src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/jajaja/global/apiPayload/exception/handler/DeliveryHandler.java
Labels: ✨ Feature

#54 ♻️ refactor: 팀 매칭 상태에 따른 알림 전송
  src/main/java/com/jajaja/domain/team/repository/TeamRepositoryCustom.java
  src/main/java/com/jajaja/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/jajaja/domain/team/service/TeamCommandServiceImpl.java
  src/main/java/com/jajaja/domain/team/service/TeamCommonService.java
  src/main/java/com/jajaja/global/scheduler/TeamExpireScheduler.java
Labels: :hammer: Refactor

#61 ✨ feat: 작성한 리뷰 조회/삭제 API
  src/main/java/com/jajaja/domain/product/controller/ProductController.java
  src/main/java/com/jajaja/domain/review/controller/ReviewController.java
  src/main/java/com/jajaja/domain/review/entity/Review.java
  src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/jajaja/domain/review/service/ReviewCommandService.java
  src/main/java/com/jajaja/domain/review/service/ReviewCommandServiceImpl.java
  src/main/java/com/jajaja/domain/review/service/ReviewQueryService.java
  src/main/java/com/jajaja/domain/review/service/ReviewQueryServiceImpl.java
  src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#64 ✨ feat: 쿠폰 관련 API
  src/main/java/com/jajaja/domain/cart/converter/CartConverter.java
  src/main/java/com/jajaja/domain/cart/dto/CartResponseDto.java
  src/main/java/com/jajaja/domain/cart/entity/Cart.java
  src/main/java/com/jajaja/domain/cart/service/CartCommandServiceImpl.java
  src/main/java/com/jajaja/domain/cart/service/CartQueryServiceImpl.java
  src/main/java/com/jajaja/domain/coupon/controller/CouponController.java
  src/main/java/com/jajaja/domain/coupon/dto/CouponApplyResponseDto.java
  src/main/java/com/jajaja/domain/coupon/dto/CouponConditionDto.java
  src/main/java/com/jajaja/domain/coupon/dto/CouponResponseDto.java
  src/main/java/com/jajaja/domain/coupon/dto/PagingCouponListResponseDto.java
  src/main/java/com/jajaja/domain/coupon/entity/Coupon.java
  src/main/java/com/jajaja/domain/coupon/repository/CouponRepository.java
  src/main/java/com/jajaja/domain/coupon/repository/CouponValidationRepository.java
  src/main/java/com/jajaja/domain/coupon/repository/CouponValidationRepositoryCustom.java
  src/main/java/com/jajaja/domain/coupon/repository/CouponValidationRepositoryImpl.java
  src/main/java/com/jajaja/domain/coupon/service/CouponCommandService.java
  src/main/java/com/jajaja/domain/coupon/service/CouponCommandServiceImpl.java
  src/main/java/com/jajaja/domain/coupon/service/CouponCommonService.java
  src/main/java/com/jajaja/domain/coupon/service/CouponQueryService.java
  src/main/java/com/jajaja/domain/coupon/service/CouponQueryServiceImpl.java
  src/main/java/com/jajaja/domain/member/repository/MemberCouponRepository.java
  src/main/java/com/jajaja/domain/member/repository/MemberCouponRepositoryCustom.java
  src/main/java/com/jajaja/domain/member/repository/MemberCouponRepositoryImpl.java
  src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/jajaja/global/apiPayload/exception/handler/CouponHandler.java
  src/main/java/com/jajaja/global/common/dto/PriceInfoDto.java
Labels: ✨ Feature

#66 ✨ feat: 포인트 관련 API, 메서드
  src/main/java/com/jajaja/domain/notification/entity/enums/NotificationType.java
  src/main/java/com/jajaja/domain/point/controller/PointController.java
  src/main/java/com/jajaja/domain/point/dto/response/PagingPointHistoryResponseDto.java
  src/main/java/com/jajaja/domain/point/dto/response/PointBalanceResponseDto.java
  src/main/java/com/jajaja/domain/point/dto/response/PointHistoryDto.java
  src/main/java/com/jajaja/domain/point/entity/Point.java
  src/main/java/com/jajaja/domain/point/entity/enums/PointType.java
  src/main/java/com/jajaja/domain/point/repository/PointRepository.java
  src/main/java/com/jajaja/domain/point/repository/PointRepositoryCustom.java
  src/main/java/com/jajaja/domain/point/repository/PointRepositoryImpl.java
  src/main/java/com/jajaja/domain/point/service/PointCommandService.java
  src/main/java/com/jajaja/domain/point/service/PointCommandServiceImpl.java
  src/main/java/com/jajaja/domain/point/service/PointQueryService.java
  src/main/java/com/jajaja/domain/point/service/PointQueryServiceImpl.java
  src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/jajaja/global/scheduler/PointExpireScheduler.java
Labels: ✨ Feature

#67 ✨ feat: 게시판 관련 API 구현
  src/main/java/com/jajaja/domain/review/controller/ReviewController.java
  src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/jajaja/domain/review/service/ReviewQueryService.java
  src/main/java/com/jajaja/domain/review/service/ReviewQueryServiceImpl.java
  src/main/java/com/jajaja/domain/team/controller/TeamController.java
  src/main/java/com/jajaja/domain/team/dto/response/TeamProductItemResponseDto.java
  src/main/java/com/jajaja/domain/team/dto/response/TeamProductListResponseDto.java
  src/main/java/com/jajaja/domain/team/repository/TeamRepositoryCustom.java
  src/main/java/com/jajaja/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/jajaja/domain/team/service/TeamQueryService.java
  src/main/java/com/jajaja/domain/team/service/TeamQueryServiceImpl.java
Labels: ✨ Feature

#71 ✨ feat: 결제 관련 API
  build.gradle
  src/main/java/com/jajaja/domain/cart/entity/CartProduct.java
  src/main/java/com/jajaja/domain/cart/service/CartCommandService.java
  src/main/java/com/jajaja/domain/cart/service/CartCommandServiceImpl.java
  src/main/java/com/jajaja/domain/coupon/service/CouponCommonService.java
  src/main/java/com/jajaja/domain/delivery/dto/DeliveryInfoDto.java
  src/main/java/com/jajaja/domain/delivery/entity/Delivery.java
  src/main/java/com/jajaja/domain/member/entity/Member.java
  src/main/java/com/jajaja/domain/member/entity/MemberCoupon.java
  src/main/java/com/jajaja/domain/member/repository/MemberCouponRepository.java
  src/main/java/com/jajaja/domain/order/controller/OrderController.java
  src/main/java/com/jajaja/domain/order/dto/request/OrderCreateRequestDto.java
  src/main/java/com/jajaja/domain/order/dto/request/OrderPrepareRequestDto.java
  src/main/java/com/jajaja/domain/order/dto/request/OrderRefundRequestDto.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderCreateResponseDto.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderDataDto.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderPrepareResponseDto.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderRefundResponseDto.java
  src/main/java/com/jajaja/domain/order/dto/response/PaymentInfoDto.java
  src/main/java/com/jajaja/domain/order/entity/Order.java
  src/main/java/com/jajaja/domain/order/entity/enums/OrderStatus.java
  src/main/java/com/jajaja/domain/order/repository/OrderRepository.java
  src/main/java/com/jajaja/domain/order/service/OrderCommandService.java
  src/main/java/com/jajaja/domain/order/service/OrderCommandServiceImpl.java
  src/main/java/com/jajaja/domain/point/entity/Point.java
  src/main/java/com/jajaja/domain/point/repository/PointRepository.java
  src/main/java/com/jajaja/domain/point/repository/PointRepositoryCustom.java
  src/main/java/com/jajaja/domain/point/repository/PointRepositoryImpl.java
  src/main/java/com/jajaja/domain/point/service/PointCommandService.java
  src/main/java/com/jajaja/domain/point/service/PointCommandServiceImpl.java
  src/main/java/com/jajaja/domain/point/service/PointQueryService.java
  src/main/java/com/jajaja/domain/point/service/PointQueryServiceImpl.java
  src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/jajaja/global/config/IamportConfig.java
  src/main/java/com/jajaja/global/scheduler/TeamExpireScheduler.java
  src/main/resources/application.yml
Labels: ✨ Feature

#74 ✨ feat: 리뷰 작성 목록 조회 API 구현
  src/main/java/com/jajaja/domain/review/controller/ReviewController.java
  src/main/java/com/jajaja/domain/review/dto/response/PagingReviewableOrderListResponseDto.java
  src/main/java/com/jajaja/domain/review/dto/response/ReviewableOrderItemDto.java
  src/main/java/com/jajaja/domain/review/dto/response/ReviewableOrderListDto.java
  src/main/java/com/jajaja/domain/review/entity/Review.java
  src/main/java/com/jajaja/domain/review/repository/ReviewRepository.java
  src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/jajaja/domain/review/service/ReviewQueryService.java
  src/main/java/com/jajaja/domain/review/service/ReviewQueryServiceImpl.java
Labels: ✨ Feature

#78 ✨ feat: CORS 설정 추가
  src/main/java/com/jajaja/global/config/CorsConfig.java
  src/main/java/com/jajaja/global/config/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: ✨ Feature

#79 🚀 deploy: dev -> main 병합
  src/main/java/com/jajaja/global/config/CorsConfig.java
  src/main/java/com/jajaja/global/config/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🚀 Deploy

#81 ✨ feat: 쿠키 sameSite, secure 설정 추가
  src/main/java/com/jajaja/global/config/security/jwt/JwtProvider.java
Labels: ✨ Feature

#82 🚀 deploy: dev -> main 병합
  src/main/java/com/jajaja/global/config/security/jwt/JwtProvider.java
Labels: 🚀 Deploy

#85 🚀 deploy: dev -> main 병합
  src/main/java/com/jajaja/global/config/security/jwt/JwtProvider.java
Labels: 🚀 Deploy

#87 ♻️ refactor: null 처리, controller 관련 변경, 에러 처리 추가
  src/main/java/com/jajaja/domain/cart/controller/CartController.java
  src/main/java/com/jajaja/domain/coupon/controller/CouponController.java
  src/main/java/com/jajaja/domain/order/controller/OrderController.java
  src/main/java/com/jajaja/domain/product/controller/ProductController.java
  src/main/java/com/jajaja/domain/product/service/ProductQueryServiceImpl.java
  src/main/java/com/jajaja/domain/review/controller/ReviewController.java
  src/main/java/com/jajaja/global/S3/controller/S3Controller.java
  src/main/java/com/jajaja/global/apiPayload/exception/ExceptionAdvice.java
Labels: :hammer: Refactor
