Repository JA-yeong-eop-JA-moeu-JA/Jajaja_BE, pull requests merged in 2025-08, with the labels that each got.

#93 ✨ feat: 쿠키 설정을 동적으로 변경
  src/main/java/com/jajaja/global/config/security/jwt/JwtProvider.java
  src/main/resources/application.yml
Labels: ✨ Feature

#96 ✨ feat: 로컬 실행용 도커 이미지 생성 스크립트 추가
  .github/workflows/ci-cd-local
Labels: 👷‍♂️ CI

#97 🚀 deploy: dev -> main 병합
  .github/workflows/ci-cd-local
Labels: 🚀 Deploy

#98 🚀 deploy: ci-cd-local 스크립트에 확장자명 추가
  .github/workflows/ci-cd-local.yml
Labels: 🚀 Deploy

#99 🚀 deploy: dev -> main 병합
  .github/workflows/ci-cd-local.yml
Labels: 🚀 Deploy

#95 ♻️ refactor: member 명칭 통일
  src/main/java/com/jajaja/domain/auth/controller/AuthController.java
  src/main/java/com/jajaja/domain/auth/dto/CustomOAuth2User.java
  src/main/java/com/jajaja/domain/auth/dto/MemberDto.java
  src/main/java/com/jajaja/domain/auth/service/AuthService.java
  src/main/java/com/jajaja/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/jajaja/domain/member/controller/MemberBusinessCategoryController.java
  src/main/java/com/jajaja/domain/member/service/MemberBusinessCategoryCommandService.java
  src/main/java/com/jajaja/domain/member/service/MemberBusinessCategoryCommandServiceImpl.java
  src/main/java/com/jajaja/domain/order/controller/OrderController.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderItemProductDto.java
  src/main/java/com/jajaja/domain/order/service/OrderQueryService.java
  src/main/java/com/jajaja/domain/order/service/OrderQueryServiceImpl.java
  src/main/java/com/jajaja/domain/product/controller/ProductController.java
  src/main/java/com/jajaja/domain/product/entity/BusinessCategory.java
  src/main/java/com/jajaja/domain/product/service/ProductQueryService.java
  src/main/java/com/jajaja/domain/product/service/ProductQueryServiceImpl.java
  src/main/java/com/jajaja/domain/review/repository/ReviewLikeRepositoryCustom.java
  src/main/java/com/jajaja/domain/review/repository/ReviewLikeRepositoryImpl.java
  src/main/java/com/jajaja/domain/review/service/ReviewQueryService.java
  src/main/java/com/jajaja/domain/review/service/ReviewQueryServiceImpl.java
  src/main/java/com/jajaja/global/config/security/jwt/JwtProvider.java
  src/main/java/com/jajaja/global/config/security/resolver/AuthArgumentResolver.java
Labels: :hammer: Refactor

#108 ♻️ refactor: ci-cd.yml 브랜치 수정
  .github/workflows/ci-cd-local.yml
  .github/workflows/ci-cd.yml
Labels: :hammer: Refactor

#106 ✨ feat: 기본프로필 관련 개선
  src/main/java/com/jajaja/domain/member/converter/MemberConverter.java
  src/main/java/com/jajaja/domain/member/dto/response/MemberInfoResponseDto.java
  src/main/java/com/jajaja/domain/member/entity/Member.java
  src/main/java/com/jajaja/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/jajaja/domain/member/service/MemberQueryServiceImpl.java
Labels: ✨ Feature

#109 🐛 fix: 데이터 반환 시 저장된 keyName으로부터 URL을 생성하도록 수정
  src/main/java/com/jajaja/domain/team/dto/response/TeamProductItemResponseDto.java
  src/main/java/com/jajaja/domain/team/service/TeamQueryServiceImpl.java
Labels: 🐞 BugFix

#115 ✨ feat: 쿠폰 조건 중 첫 구매 타입 추가
  src/main/java/com/jajaja/domain/coupon/entity/enums/ConditionType.java
  src/main/java/com/jajaja/domain/coupon/service/CouponCommonService.java
  src/main/java/com/jajaja/domain/order/repository/OrderRepository.java
Labels: ✨ Feature

#117 ✨ Feat: 알림 목록 조회 API 페이징 추가
  src/main/java/com/jajaja/domain/notification/controller/NotificationController.java
  src/main/java/com/jajaja/domain/notification/dto/request/NotificationCreateRequestDto.java
  src/main/java/com/jajaja/domain/notification/dto/response/NotificationResponseDto.java
  src/main/java/com/jajaja/domain/notification/dto/response/PagingNotificationResponseDto.java
  src/main/java/com/jajaja/domain/notification/dto/response/UnreadCountResponseDto.java
  src/main/java/com/jajaja/domain/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/jajaja/domain/notification/repository/NotificationRepositoryImpl.java
  src/main/java/com/jajaja/domain/notification/service/NotificationService.java
  src/main/java/com/jajaja/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/jajaja/domain/team/service/TeamCommonService.java
  src/main/java/com/jajaja/global/scheduler/PointExpireScheduler.java
  src/main/java/com/jajaja/global/scheduler/TeamExpireScheduler.java
Labels: ✨ Feature

#120 ♻️ refactor: 프로필 Keyname 전달할 수 있도록 DTO 수정
  src/main/java/com/jajaja/domain/member/service/MemberQueryService.java
  src/main/java/com/jajaja/domain/member/service/MemberQueryServiceImpl.java
  src/main/java/com/jajaja/domain/product/dto/response/ProductDetailResponseDto.java
  src/main/java/com/jajaja/domain/product/service/ProductQueryServiceImpl.java
  src/main/java/com/jajaja/domain/review/dto/response/ReviewItemDto.java
  src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/jajaja/domain/team/dto/response/TeamListDto.java
Labels: :hammer: Refactor

#129 ♻️ refactor: 팀 매칭 시, 리더에게만 알림 보내도록 수정
  src/main/java/com/jajaja/domain/team/service/TeamCommonService.java
Labels: :hammer: Refactor

#130 ♻️ refactor: 리뷰 상세 조회 API에 이미지 정적 URL 변환 적용
  src/main/java/com/jajaja/domain/review/service/ReviewQueryServiceImpl.java
Labels: :hammer: Refactor

#133 ♻️ refactor: Swagger 태그 문서화 통일 작업
  src/main/java/com/jajaja/domain/auth/controller/AuthController.java
  src/main/java/com/jajaja/domain/cart/controller/CartController.java
  src/main/java/com/jajaja/domain/coupon/controller/CouponController.java
  src/main/java/com/jajaja/domain/delivery/controller/DeliveryController.java
  src/main/java/com/jajaja/domain/member/controller/MemberBusinessCategoryController.java
  src/main/java/com/jajaja/domain/member/controller/MemberController.java
  src/main/java/com/jajaja/domain/notification/controller/NotificationController.java
  src/main/java/com/jajaja/domain/order/controller/OrderProductsController.java
  src/main/java/com/jajaja/domain/point/controller/PointController.java
  src/main/java/com/jajaja/domain/product/controller/CategoryController.java
  src/main/java/com/jajaja/domain/product/controller/ProductController.java
  src/main/java/com/jajaja/domain/review/controller/ReviewController.java
  src/main/java/com/jajaja/domain/search/controller/SearchController.java
  src/main/java/com/jajaja/domain/team/controller/TeamController.java
  src/main/java/com/jajaja/global/S3/controller/S3Controller.java
  src/main/java/com/jajaja/global/common/health/HealthController.java
Labels: :hammer: Refactor

#136 ✨ Feat: 상품 검색 API 페이징 추가
  src/main/java/com/jajaja/domain/search/controller/SearchController.java
  src/main/java/com/jajaja/domain/search/dto/PagingSearchProductListResponseDto.java
  src/main/java/com/jajaja/domain/search/repository/SearchRepositoryCustom.java
  src/main/java/com/jajaja/domain/search/repository/SearchRepositoryCustomImpl.java
  src/main/java/com/jajaja/domain/search/service/SearchService.java
  src/main/java/com/jajaja/domain/search/service/SearchServiceImpl.java
Labels: ✨ Feature

#138 ✨ feat: 결제 준비, 결제 승인, 환불 API 수정
  build.gradle
  src/main/java/com/jajaja/domain/cart/dto/CartProductResponseDto.java
  src/main/java/com/jajaja/domain/cart/entity/Cart.java
  src/main/java/com/jajaja/domain/cart/entity/CartProduct.java
  src/main/java/com/jajaja/domain/coupon/service/CouponCommonService.java
  src/main/java/com/jajaja/domain/order/controller/OrderController.java
  src/main/java/com/jajaja/domain/order/dto/request/OrderApproveRequestDto.java
  src/main/java/com/jajaja/domain/order/dto/request/OrderCreateRequestDto.java
  src/main/java/com/jajaja/domain/order/dto/request/OrderRefundRequestDto.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderApproveResponseDto.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderCreateResponseDto.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderDataDto.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderDetailResponseDto.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderPrepareResponseDto.java
  src/main/java/com/jajaja/domain/order/dto/response/OrderRefundResponseDto.java
  src/main/java/com/jajaja/domain/order/dto/response/PaymentInfoDto.java
  src/main/java/com/jajaja/domain/order/dto/response/TossPayments/CardDto.java
  src/main/java/com/jajaja/domain/order/dto/response/TossPayments/EasyPayDto.java
  src/main/java/com/jajaja/domain/order/dto/response/TossPayments/PaymentFailureDto.java
  src/main/java/com/jajaja/domain/order/dto/response/TossPayments/PaymentResponseDto.java
  src/main/java/com/jajaja/domain/order/entity/Order.java
  src/main/java/com/jajaja/domain/order/entity/enums/OrderStatus.java
  src/main/java/com/jajaja/domain/order/entity/enums/PaymentMethod.java
  src/main/java/com/jajaja/domain/order/repository/OrderRepository.java
  src/main/java/com/jajaja/domain/order/service/OrderCommandService.java
  src/main/java/com/jajaja/domain/order/service/OrderCommandServiceImpl.java
  src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/jajaja/global/apiPayload/exception/custom/TossPaymentException.java
  src/main/java/com/jajaja/global/config/IamportConfig.java
  src/main/java/com/jajaja/global/config/RestTemplateConfig.java
  src/main/java/com/jajaja/global/config/TossPaymentsConfig.java
  src/main/java/com/jajaja/global/scheduler/TeamExpireScheduler.java
  src/main/resources/application.yml
Labels: ✨ Feature

#140 ♻️ refactor: 리뷰 관련 API 수정
  src/main/java/com/jajaja/domain/review/dto/request/ReviewCreateRequestDto.java
  src/main/java/com/jajaja/domain/review/dto/response/ReviewItemDto.java
  src/main/java/com/jajaja/domain/review/dto/response/ReviewableOrderItemDto.java
  src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/jajaja/domain/review/service/ReviewCommandServiceImpl.java
  src/main/java/com/jajaja/domain/review/service/ReviewCommonServiceImpl.java
Labels: :hammer: Refactor

#141 🐛 fix: config 명칭 에러 수정
  src/main/java/com/jajaja/domain/order/service/OrderCommandServiceImpl.java
  src/main/java/com/jajaja/global/config/TossPaymentsConfig.java
Labels: 🐞 BugFix

#157 🐛 fix: 결제 API에서 금액 확인 로직 수정
  src/main/java/com/jajaja/domain/order/service/OrderCommandServiceImpl.java
Labels: 🐞 BugFix

#162 🐛 fix: thumbnail, image URL 길이 조건 수정
  src/main/java/com/jajaja/domain/product/entity/Product.java
Labels: 🐞 BugFix

#172 Update README.md
  README.md
Labels: 🛠️ Chore

#166 ✨ feat: 최초 로그인(회원가입) 후 약관페이지 분기
  src/main/java/com/jajaja/domain/member/controller/MemberController.java
  src/main/java/com/jajaja/domain/member/converter/MemberConverter.java
  src/main/java/com/jajaja/domain/member/entity/Member.java
  src/main/java/com/jajaja/domain/member/service/MemberCommandService.java
  src/main/java/com/jajaja/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/jajaja/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/jajaja/global/security/SecurityConfig.java
  src/main/java/com/jajaja/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/jajaja/global/security/jwt/JwtProperties.java
  src/main/java/com/jajaja/global/security/jwt/JwtProvider.java
  src/main/java/com/jajaja/global/security/jwt/TokenType.java
  src/main/java/com/jajaja/global/security/oauth/CustomOAuth2SuccessHandler.java
  src/main/resources/application.yml
Labels: ✨ Feature

#180 ✨ feat: 카카오 닉네임을 받아올 수 있도록 수정
  src/main/java/com/jajaja/domain/auth/dto/GoogleResponseDto.java
  src/main/java/com/jajaja/domain/auth/dto/KakaoResponseDto.java
  src/main/java/com/jajaja/domain/auth/dto/OAuth2ResponseDto.java
  src/main/java/com/jajaja/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/jajaja/domain/member/converter/MemberConverter.java
  src/main/resources/application.yml
Labels: ✨ Feature

#182 ♻️ Refactor: 홈 상품 리스트 조회 API 로직 개선
  src/main/java/com/jajaja/domain/product/service/ProductQueryServiceImpl.java
Labels: :hammer: Refactor

#185 ✨ feat: 장바구니 상품 추가/수정 시 반환값 수정, 결제시간이 만료된 주문의 상태가 자동으로 변경되는 scheduler 추가
  src/main/java/com/jajaja/domain/cart/controller/CartController.java
  src/main/java/com/jajaja/domain/cart/service/CartCommandService.java
  src/main/java/com/jajaja/domain/cart/service/CartCommandServiceImpl.java
  src/main/java/com/jajaja/domain/order/repository/OrderRepository.java
  src/main/java/com/jajaja/domain/order/service/OrderCommandService.java
  src/main/java/com/jajaja/domain/order/service/OrderCommandServiceImpl.java
  src/main/java/com/jajaja/global/scheduler/OrderExpireScheduler.java
Labels: ✨ Feature

#189 ♻️ Refactor: 리뷰 작성 API 추가 수정
  src/main/java/com/jajaja/domain/review/repository/ReviewRepositoryImpl.java
Labels: :hammer: Refactor

#195 ✨ feat: 쿠폰 조회 시 사용 가능 여부 함께 반환
  src/main/java/com/jajaja/domain/cart/converter/CartConverter.java
  src/main/java/com/jajaja/domain/coupon/dto/CouponResponseDto.java
  src/main/java/com/jajaja/domain/coupon/service/CouponCommonService.java
  src/main/java/com/jajaja/domain/coupon/service/CouponQueryServiceImpl.java
Labels: ✨ Feature

#202 🐛 fix: 주문 배송 스케줄링 로직을 OrderScheduleService로 분리
  src/main/java/com/jajaja/domain/order/service/OrderCommandServiceImpl.java
  src/main/java/com/jajaja/domain/order/service/OrderScheduleService.java
  src/main/java/com/jajaja/domain/team/service/TeamCommandService.java
Labels: ✨ Feature

#205 ✨ feat: 쿠폰 적용 관련, 팀 결제 관련 수정 사항 적용
  src/main/java/com/jajaja/domain/cart/entity/Cart.java
  src/main/java/com/jajaja/domain/cart/service/CartCommandServiceImpl.java
  src/main/java/com/jajaja/domain/coupon/controller/CouponController.java
  src/main/java/com/jajaja/domain/coupon/dto/CouponApplyRequestDto.java
  src/main/java/com/jajaja/domain/coupon/entity/Coupon.java
  src/main/java/com/jajaja/domain/coupon/service/CouponCommandService.java
  src/main/java/com/jajaja/domain/coupon/service/CouponCommandServiceImpl.java
  src/main/java/com/jajaja/domain/coupon/service/CouponCommonService.java
  src/main/java/com/jajaja/domain/member/entity/MemberCoupon.java
  src/main/java/com/jajaja/domain/order/service/OrderCommandServiceImpl.java
Labels: 🐞 BugFix, ✨ Feature
